name: Testando update homol
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push main branch into production
      uses: codingforentrepreneurs/action-branch-to-branch@main
      with:
        dest_branch: 'homologation'
        source_branch: 'main'
        commit_message: 'Release production version'
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}