name: Update homologation/tracking with master
on:
  push:
    branches:
      - master
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push master branch into homologation
      uses: codingforentrepreneurs/action-branch-to-branch@main
      with:
        dest_branch: 'homologation/tracking'
        source_branch: 'master'
        commit_message: 'Update homol with master'
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}